### PR TITLE
PLAT-9957: pull: include .vscode/tasks.json

### PR DESCRIPTION
**Pull request by Daniel-Knights**
This PR includes `.vscode/tasks.json` when pulling from the template.

### CODE REVIEW

**Review by luiscamachopt — APPROVED** [review]
Looks good to me but there's already another PR by Mike to align the playground.

**Comment by Daniel-Knights** [comment]
> Looks good to me but there's already another PR by Mike to align the playground.

Would you rather playground changes generally go in separate PRs? I can revert them if so. I've typically included playground changes with each PR, as they're just for messing about locally

**Comment by luiscamachopt** [comment]
@Daniel-Knights either is fine with me. Although as more people work on this repo, it probably helps to align separately so everyone benefits earlier and makes PRs simpler to review. If you rebase after the other one is merged, they should just go away.

**Comment by Daniel-Knights** [comment]
Okay, I'll wait for @mstrong98 to merge the playground changes and rebase before merging this PR

**Review by mstrong98 — APPROVED** [review]
@Daniel-Knights Thanks Dan, go ahead and merge this. I'll just close the other PR.

**Pull request merged**
